### ISSUE TITLE
Content for Week 4

### ISSUE THREAD

**Issue by timmcginley** [timmcginley/41934#15]
Hey Christian @ocni-dtu 

Good to catch up and great that you can do a lecture for the students in week 4.

Please edit the [week 4] schedule with some bullets about your presentation.

Also put in the time that you can do for consultation / talking to them? a couple of hours would be great, but I know you are super busy and really appreciate what you can manage.

*N.B. the links in the repo are for github pages so they don't work in github.com, its a bit confusing but works in the end....*

[week 4]: https://github.com/timmcginley/41934/tree/main/Schedule/04

**Comment by timmcginley** [comment]
Thanks Christian,

Please be aware that repo is public and GPL3.0 - I can put the pres on Dtu
Learn (the new campusnet) to bury it if you would like?

Super cool if you are ok having it on there though :)

Look forward to catching up on monday.

Cheers

Tim

**Comment by ocni-dtu** [comment]
No problem - it can be public :)
