### ISSUE TITLE
Content for week 6

### ISSUE THREAD

**Issue by timmcginley** [timmcginley/41934#17]
Hej Ann-Britt

Thanks for agreeing to do a lecture for the students in week 6 about:

*  your thesis
* work in the office
* IfcOpenShell use in practice

Please edit the [week 6] schedule with some bullets about your presentation.

*N.B. the links in the repo are for github pages so they don't work in github.com, its a bit confusing but works in the end....*

[week 6]: https://github.com/timmcginley/41934/tree/main/Schedule/06

**Comment by mdjska** [comment]
Hi @Vejlgaarda, are you still planning on doing a presentation for the students on Monday? It's just going to be me, so I wanted to know what to plan for :)
